### PR TITLE
Prefer using calldata instead of memory

### PR DESCRIPTION
**Pull request by k06a**
Sometimes it's a lot cheaper in terms of gas, sometimes it's a bit.

I was made to decrease `runs` setting in hardhat config due slightly increased bytecode size (out of 24kb limit).

### CODE REVIEW

**Comment by hensha256** [comment]
hey @k06a! Thanks so much for making this pull request. Don't worry about the hardhat CI failing - thats a problem we're having with fork PRs at the moment. However the other 2 should be passing. It looks like the forge config needs to be updated because the bytecode size is over 24kb :)

**Comment by hensha256** [comment]
Hey @k06a! We're interested in getting these changes merged, but the fact that tests won't run on fork PRs make it more complex for us to review.
I was wondering if you would mind me making a new branch `prefer-calldata` in the repo, and merging your PR into that branch? That way i can set up a new PR into `main` where tests run, and play around with your changes a bit.

**Comment by k06a** [comment]
@hensha256 I don’t know what exactly prevents tests being executed in your CI, you can change PR target branch by editing this PR and merge it to the different branch.

**Comment by hensha256** [comment]
@k06a its due to the fact that Github does not allow fork branches to access Github secrets for security reasons :) 
Thank you! Will make a new branch and PR for this now

**Review by hensha256 — APPROVED** [review]
Merging to `prefer-calldata` so we can run CI

**Pull request merged**
